name: Make test build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          export TERM=linux
          sudo apt-get update
          sudo apt-get install kpartx qemu-user-static qemu-utils
      - name: Set env
        run: |
          curl https://updater.home-assistant.io/ -o /tmp/version.js
          VERSION=$(jq .version /tmp/version.js)
          echo "::set-env name=VERSION::${VERSION}"
          LOG=$(jq '."release-notes"' /tmp/version.js)
          echo "::set-env name=LOG::${LOG}"
          PACKER_VERSION="1.5.4"
          echo "::set-env name=PACKER_VERSION::${PACKER_VERSION}"
          DEB_IMG="https://cloud.debian.org/images/cloud/buster/20200210-166/debian-10-generic-arm64-20200210-166.qcow2"
          echo "::set-env name=B_IMG::${DEB_IMG}"
      - name: Packer ${{ env.PACKER_VERSION }} setup
        run: |
          PACKER_VERSION="1.5.4"
          curl https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -o /tmp/packer.zip
          unzip /tmp/packer.zip -d /tmp
          sudo mv /tmp/packer /usr/bin/packer
          git clone https://github.com/foreign-sub/packer-builder-arm-image.git /tmp/packer-builder-arm-image
          cd /tmp/packer-builder-arm-image && git checkout testing
          cd /tmp/packer-builder-arm-image && go get -d ./... && go build
          sudo cp /tmp/packer-builder-arm-image/packer-builder-arm-image /usr/bin
      - name: Download image
        run: |
          #UBU_IMG="https://cloud-images.ubuntu.com/eoan/current/eoan-server-cloudimg-arm64.img"
          curl ${{ env.B_IMG }} -o /tmp/arm64.qcow2
          qemu-img convert /tmp/arm64.qcow2 /home/runner/work/ha_fbx/arm64.img
          #
          #curl ${UBU_IMG} -o /home/runner/work/ha_fbx/arm64.img
      - name: Build image for ${{ env.VERSION }}
        run: |
          mkdir -p /tmp/mnt
          pwd
          cd tasks && sudo /usr/bin/packer build ha_fbx_arm64.json
          sudo mv output-hafbx/image hafbx-debian-$(VERSION).img
          qemu-img convert hafbx-debian-$(VERSION).img hafbx-debian-$(VERSION).qcow2
          sudo sha256sum hafbx-debian-$(VERSION).qcow2 > hafbx-debian-$(VERSION).sha256
          sudo zip hafbx-debian-$(VERSION).zip hafbx-debian-$(VERSION).sha256 hafbx-debian-$(VERSION).qcow2
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     release_name: Image for ${{ env.VERSION }}
      #     body: |
      #       ${{ env.LOG }}
      #     draft: false
      #     prerelease: true
      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./hafbx-debian-${{ env.VERSION }}.zip
      #     asset_name: hafbx-debian-${{ env.VERSION }}.zip
      #     asset_content_type: application/zip

      - name: Clean
        run: |
          echo "Build done"
